name: 'Fortify AST Scan'
description: 'Find and fix vulnerabilities to build secure software with Fortify Code Security.'
author: 'Fortify'
inputs:
  sast-scan:
    description: 'Run a SAST scan, takes either true or false (default)'
    default: 'false'
    required: false
  debricked-sca-scan:
    description: 'Run a Debricked Software Composition Analysis, takes either true or false (default)'
    default: 'false'
    required: false
runs:
  using: composite
  steps:
    - uses: patricioperezv/boaboa-fortify-action/fod-sast-scan@v1.5.2
      if: inputs['sast-scan']=='true' && env.FOD_URL 
      env:
        DO_DEBRICKED_SCAN: ${{ inputs['debricked-sca-scan'] }}
    - uses: patricioperezv/boaboa-fortify-action/sc-sast-scan@v1.5.2
      if: inputs['sast-scan']=='true' && env.SSC_URL 
      env:
        DO_DEBRICKED_SCAN: ${{ inputs['debricked-sca-scan'] }}
    - uses: patricioperezv/boaboa-fortify-action/ssc-debricked-scan@v1.5.2
      if: inputs['sast-scan']=='false' && inputs['debricked-sca-scan']=='true' && env.SSC_URL 
        
branding:
  icon: 'shield'
  color: 'blue'

