name: 'Export SSC vulnerability data to GitHub'
description: 'Export SSC vulnerability data to GitHub'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: patricioperezv/boaboa-fortify-action/internal/set-ssc-var-defaults@v1.3.1
    - uses: patricioperezv/boaboa-fortify-action/setup@v1.3.1
      with:
        export-path: false
        fcli: action-default
    - uses: patricioperezv/boaboa-fortify-action/internal/ssc-login@v1.3.1
    - uses: patricioperezv/boaboa-fortify-action/internal/run-script@v1.3.1
      with:
        script: export.sh
      env: 
        PRODUCT: ssc
        DEFAULT_OPTS: --av "${{env.SSC_APPVERSION}}" -f ./gh-fortify-sast.sarif
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./gh-fortify-sast.sarif

    # Optionally store the generated file for troubleshooting purposes.
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.job }}-${{ strategy.job-index }}-sarif-files
        path: ./gh-fortify-sast.sarif

branding:
  icon: 'shield'
  color: 'blue'

