name: 'Perform SAST scan'
description: 'Perform a SAST scan on ScanCentral SAST'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: patricioperezv/boaboa-fortify-action/internal/set-ssc-var-defaults@v1.4.0
    - uses: patricioperezv/boaboa-fortify-action/setup@v1.4.0
      with:
        export-path: false
        fcli: action-default
        debricked-cli: ${{ env.DO_DEBRICKED_SCAN=='true' && 'action-default' || 'skip' }}
    - uses: patricioperezv/boaboa-fortify-action/internal/ssc-login@v1.4.0
    - uses: patricioperezv/boaboa-fortify-action/internal/sc-sast-login@v1.4.0
    - uses: patricioperezv/boaboa-fortify-action/package@v1.4.0
    - uses: patricioperezv/boaboa-fortify-action/internal/run-script@v1.4.0
      with:
        script: sc-sast-and-debricked-scan.sh
      env: 
        DO_SC_SAST_SCAN: true
        GITHUB_TOKEN: ${{ github.token }}
    - if: env.DO_EXPORT == 'true'
      uses: patricioperezv/boaboa-fortify-action/ssc-export@v1.4.0
        
branding:
  icon: 'shield'
  color: 'blue'

